### PR TITLE
Fix menu position and grid icon

### PR DESCRIPTION
**Pull request by JuanCSUCoder**

### CODE REVIEW

**Comment by icysapphire** [comment]
@buenoudg @JCSUCoder Sorry guys, made a little mess because I was working on a bug (grid no longer properly resizing with chat open) and I didn't see your work.
I am going to release the new version in the store, could you check it out before? Thank you!

**Comment by buenoudg** [comment]
Everything looks good here with 1.40 👍🏼

IIUC pinning doesn't work when the grid is on. Maybe it should be hidden (only when the grid is on)?

**Comment by JuanCSUCoder** [comment]
v1.40 works fine.

**Comment by icysapphire** [comment]
> IIUC pinning doesn't work when the grid is on. Maybe it should be hidden (only when the grid is on)?

Yes, it should, but I was thinking of fixing that feature...

**Comment by atnbueno** [comment]
> Yes, it should, but I was thinking of fixing that feature...

If you insist 😁

**Pull request closed without merging**
